// code by ntu ael

#ifndef SHARED_ADCS_H
#define SHARED_ADCS_H

#define XDATA_ADCS_HK_OFFSET  100
#define XDATA_ADCS_HK_LENGTH  181

#define XDATA_ADCS_TAITIME_OFFSET   XDATA_ADCS_HK_OFFSET

#define XDATA_ADCS_MET_OFFSET   300
#define XDATA_ADCS_MET_LENGTH   115

#define XDATA_ADCS_ADS_OFFSET   500
#define XDATA_ADCS_ADS_LENGTH   101

#define XDATA_ADCS_EKF_OFFSET   610
#define XDATA_ADCS_EKF_LENGTH   180

#define XDATA_ADCS_ACT_OFFSET   800
#define XDATA_ADCS_ACT_LENGTH   135

#define XDATA_ADCS_ACS_OFFSET   940
#define XDATA_ADCS_ACS_LENGTH   71

#define XDATA_ADCS_ACS2_OFFSET  1020
#define XDATA_ADCS_ACS2_LENGTH  144

#define XDATA_ADCS_ACS3_OFFSET  1200
#define XDATA_ADCS_ACS3_LENGTH  48

#define XDATA_ADCS_GPS_OFFSET   1250
#define XDATA_ADCS_GPS_LENGTH   98

#define XDATA_ADCS_BEACON_OFFSET  1342
#define XDATA_ADCS_BEACON_LENGTH  6

#define XDATA_ADCS_GPS_ISAVAILABLE  XDATA_ADCS_GPS_OFFSET

#define XDATA_ADCS_IMU_OFFSET   1385
#define XDATA_ADCS_IMU_LENGTH   225

#define XDATA_ADCS_GPSBIN_OFFSET  1700
#define XDATA_ADCS_GPSBIN_LENGTH  225

#define XDATA_ADCS_SUNSENSOR1_OFFSET  2376
#define XDATA_ADCS_SUNSENSOR1_LENGTH  36

#define XDATA_ADCS_SUNSENSOR2_OFFSET  2520
#define XDATA_ADCS_SUNSENSOR2_LENGTH  120

#endif
